### ISSUE TITLE
a download issue about the model

### ISSUE THREAD

**Issue by xuhan20010421** [thomas-yanxin/the-eye-knows-the-garbage#2]
why can't download the vital model.zip? it's all failure

**Comment by thomas-yanxin** [comment]
本项目所用程序均已上传百度网盘，若下载有困难，可使用百度网盘下载。
链接：https://pan.baidu.com/s/1KcGOU4DLFQuSb3YZeGktqA 
提取码：reqq 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by xuhan20010421** [comment]
thank you very much!
