### ISSUE TITLE
无法下载模型文件，以前提供的百度盘连接也失效了

### ISSUE THREAD

**Issue by xueminghui** [thomas-yanxin/the-eye-knows-the-garbage#4]

**Comment by thomas-yanxin** [comment]
链接：https://pan.baidu.com/s/1lMISiDhmkuZqmU8DdzNgLQ?pwd=vh75 
提取码：vh75

**Comment by xueminghui** [comment]
> 链接：https://pan.baidu.com/s/1lMISiDhmkuZqmU8DdzNgLQ?pwd=vh75 
> 
> 提取码：vh75

谢谢了
